create table dish (
	id INT PRIMARY KEY AUTO_INCREMENT UNIQUE,
	_id VARCHAR(50),
	Name VARCHAR(50),
	Description TEXT,
	Price DECIMAL(5,2),
	Category TEXT,
	Availability TEXT,
	WaitTimeMinutes INT,
	SoldOut INT,
	Rating DECIMAL(2,1),
	Created DATETIME,
	Changed DATETIME
);
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (1, '1HE9JrGTRpDLLhxPcdjeKwm5eE2NMNYbm6', 'Wine - Trimbach Pinot Blanc', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 446.59, 'quam nec dui luctus rutrum nulla tellus', 'sagittis dui vel nisl duis', 100, 0, 1.9, '2021-10-19 04:42:51', '2022-04-19 11:57:16');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (2, '1Pqx27ZiidqFL4YecSvDDAhhExDRF4uruA', 'Lid Coffee Cup 8oz Blk', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 296.84, 'nullam varius nulla facilisi cras non velit', 'lacus at turpis donec posuere', 21, 0, 4.1, '2021-10-14 22:07:00', '2022-05-19 07:50:37');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (3, '1CFXu1XbDXFuWXST5pyM682pJJBjEruhiC', 'Mushroom - Enoki, Fresh', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 30.09, 'tempus semper est quam pharetra magna', 'nunc vestibulum ante ipsum primis in faucibus', 32, 1, 2.2, '2021-09-24 22:30:01', '2021-10-31 13:47:17');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (4, '195n5j25imVLXdSXBramVoPKLCps4sS6X3', 'Sardines', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 204.44, 'parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum', 'fermentum donec ut mauris eget', 83, 1, 4.0, '2022-03-20 09:52:12', '2022-07-04 12:18:41');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (5, '1Q1ygYZUBquSp9MUs2C1afnqY24bnCXhsa', 'Flour - Cake', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 83.76, 'tincidunt eget tempus vel pede morbi porttitor lorem id ligula', 'duis faucibus accumsan odio curabitur', 78, 0, 1.3, '2021-12-22 14:49:31', '2021-09-30 21:23:51');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (6, '17GZ9GDZXoAt77JkFf1C4y4cRCBHGMvYwB', 'Milk - Chocolate 500ml', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 233.91, 'tincidunt nulla mollis molestie lorem quisque ut erat', 'ipsum dolor sit amet consectetuer adipiscing', 99, 1, 4.2, '2021-10-18 14:11:47', '2022-02-23 06:10:00');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (7, '1BtEUYFNancJZhQtrzqsEzxooEmd1BCjqP', 'Galliano', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', 100.48, 'id massa id nisl venenatis lacinia', 'hac habitasse platea dictumst morbi vestibulum velit id', 10, 0, 3.3, '2021-12-20 12:16:22', '2022-03-12 14:23:39');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (8, '1KDEnCrj3Dg2nar9VQqjBmdRuwFig1vBuf', 'Garam Marsala', 'In congue. Etiam justo. Etiam pretium iaculis justo.', 221.91, 'viverra dapibus nulla suscipit ligula in', 'duis faucibus accumsan odio curabitur convallis duis consequat', 11, 1, 2.6, '2022-03-18 00:00:49', '2022-07-17 05:31:30');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (9, '1G689isZ8f5XM4t8hCosqHnxxf8Z9Y3tZ9', 'Pepper - Roasted Red', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 325.54, 'cubilia curae duis faucibus accumsan odio curabitur convallis duis', 'aliquam non mauris morbi non lectus aliquam sit amet', 67, 1, 2.1, '2021-11-14 06:06:03', '2022-02-12 15:44:16');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (10, '1uQgNpqs7QYXwjSGD5F3885NbHJEw5Lcp', 'Instant Coffee', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 456.78, 'suspendisse ornare consequat lectus in est risus auctor', 'nulla tempus vivamus in felis', 24, 1, 1.2, '2021-12-01 23:56:18', '2022-08-05 01:14:24');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (11, '178YoJPSquK2Nzc4rTkSx7qwXGh9TKKHrP', 'Cup - 8oz Coffee Perforated', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 172.57, 'et commodo vulputate justo in', 'aliquam augue quam sollicitudin vitae consectetuer eget rutrum at', 63, 1, 1.1, '2021-11-13 23:06:10', '2021-11-27 13:21:38');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (12, '1H5VN2WuVyXtrVKB7mA2YG7HM3hCrzJe4C', 'Cake Slab', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 99.8, 'mattis odio donec vitae nisi nam', 'sed interdum venenatis turpis enim', 100, 0, 4.8, '2022-08-11 13:53:08', '2021-12-01 21:52:50');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (13, '1J6wptTLGVD6CJ1Hrc5qwdzvxVBfFEes39', 'Wine - Semi Dry Riesling Vineland', 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 277.35, 'vulputate elementum nullam varius nulla facilisi cras non velit', 'diam vitae quam suspendisse potenti nullam porttitor', 65, 0, 2.9, '2022-03-24 00:25:15', '2022-08-10 22:02:38');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (14, '15iK6DHsM7x2Fw6gfmAG7Rcx8KAjgJWBHL', 'Pumpkin', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 60.25, 'morbi non quam nec dui luctus rutrum nulla', 'dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien', 70, 1, 4.8, '2022-07-15 07:33:07', '2022-04-26 23:28:37');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (15, '1MihP2naJHjDKLdkUFEkg5zcp6AGSVk1oo', 'Pork - Liver', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', 151.56, 'cras non velit nec nisi vulputate nonummy maecenas', 'id lobortis convallis tortor risus', 54, 0, 3.7, '2022-02-23 14:23:08', '2022-06-06 22:54:10');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (16, '1LXbRNzF1bRt3u27ZEt1D21nUgM5N4hnfN', 'Oven Mitts 17 Inch', 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', 276.75, 'lacinia aenean sit amet justo morbi ut odio cras', 'augue quam sollicitudin vitae consectetuer eget rutrum', 81, 1, 3.5, '2022-03-09 10:26:11', '2022-09-06 02:49:34');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (17, '1LSQHMZcKeY4cFSj5Vabbya27q5Yig2bPz', 'Lobster - Baby, Boiled', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', 204.65, 'posuere cubilia curae nulla dapibus dolor', 'in blandit ultrices enim lorem ipsum', 85, 0, 4.6, '2021-10-28 07:10:18', '2022-07-09 10:22:07');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (18, '1NEJK2eLWVQgfDJFYqBn59REhKYeVpXAEk', 'Cookies - Amaretto', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 281.35, 'ut tellus nulla ut erat id', 'erat id mauris vulputate elementum nullam varius nulla', 18, 0, 2.8, '2022-06-06 13:05:30', '2021-09-22 02:57:27');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (19, '17cEmNjTFWiidkNQPdppPsTXKjYYTJiy8b', 'Bacardi Breezer - Tropical', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 427.3, 'volutpat dui maecenas tristique est et tempus semper est', 'sapien placerat ante nulla justo', 20, 0, 3.7, '2021-11-29 23:52:11', '2022-08-08 14:04:42');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (20, '1KUdcpkHnT56hoAceHFxRTRMqYchtvioZV', 'Foam Espresso Cup Plain White', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 183.31, 'posuere nonummy integer non velit donec diam', 'tellus nulla ut erat id mauris vulputate elementum nullam varius', 56, 1, 5.0, '2022-04-29 10:32:23', '2022-02-17 21:57:57');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (21, '14uP3uwhcWZ9ZqZkhH5pqPkpnivwTtEnGh', 'Soup - Cream Of Potato / Leek', 'Fusce consequat. Nulla nisl. Nunc nisl.', 43.67, 'amet consectetuer adipiscing elit proin interdum mauris non', 'adipiscing lorem vitae mattis nibh ligula nec sem', 28, 1, 2.6, '2021-12-10 06:30:42', '2022-06-16 00:09:09');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (22, '1N9XZQ9Bz6DNU1CGnGFPVa4XevcuVYBJDp', 'Cheese - Bakers Cream Cheese', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 86.78, 'phasellus id sapien in sapien iaculis', 'primis in faucibus orci luctus et', 59, 1, 4.7, '2022-04-27 17:40:06', '2021-11-07 11:48:37');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (23, '1DSWVkJM65E2xRbbGYxzGPfCYewrUVDG75', 'Nut - Walnut, Pieces', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', 453.3, 'dui vel nisl duis ac nibh fusce lacus purus aliquet', 'porttitor lacus at turpis donec posuere metus vitae ipsum aliquam', 20, 1, 3.9, '2022-04-21 10:18:38', '2022-08-16 22:18:32');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (24, '1Fmd2MYKMtkScu1vDgKe7ydTJfjagKjoBE', 'Chocolate - Dark', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 399.72, 'consectetuer eget rutrum at lorem integer', 'luctus et ultrices posuere cubilia curae mauris viverra', 10, 1, 2.1, '2021-11-10 23:47:24', '2022-07-03 02:06:18');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (25, '1HVQBtAU57CvnQx6jDEPtrizcbrzzuR1DQ', 'Sprouts - Peppercress', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', 398.13, 'sapien a libero nam dui proin leo odio porttitor id', 'est donec odio justo sollicitudin ut', 99, 1, 3.1, '2022-08-29 14:43:56', '2021-11-12 22:18:10');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (26, '1Etit5FCAqeeWfuuL9KPNkMbybKS3MnBff', 'Soup - Campbells Mac N Cheese', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 429.45, 'dui vel nisl duis ac nibh fusce lacus purus aliquet', 'nunc vestibulum ante ipsum primis in faucibus', 10, 0, 2.9, '2021-10-19 10:30:57', '2022-09-14 08:29:15');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (27, '196HPhf7AC33PcMA5no8vsAZQyf63B5FCU', 'Dried Apple', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 281.47, 'odio curabitur convallis duis consequat dui nec', 'bibendum morbi non quam nec dui luctus rutrum nulla', 89, 0, 3.7, '2021-11-25 09:14:38', '2021-11-04 08:39:37');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (28, '1Kv8jwe3SdaSvfPYDfPX4V9C9sxJkVKnCX', 'Beef - Ox Tail, Frozen', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 496.27, 'amet justo morbi ut odio', 'justo lacinia eget tincidunt eget tempus', 4, 0, 1.3, '2022-06-25 08:45:52', '2022-08-14 17:40:19');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (29, '12gSP8e6ANn9Ufc7NhjS6Nz6h5f33nGAkN', 'The Pop Shoppe - Grape', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 338.34, 'dolor sit amet consectetuer adipiscing elit', 'cubilia curae mauris viverra diam', 58, 0, 1.3, '2021-11-22 03:10:39', '2021-11-03 18:32:08');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (30, '1CB9oBshaKKdyfeMfNmg7pqT5eegQ1AKyZ', 'Basil - Fresh', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 495.68, 'nulla eget eros elementum pellentesque quisque porta volutpat erat', 'in hac habitasse platea dictumst aliquam augue quam sollicitudin', 77, 0, 4.7, '2022-01-12 07:47:24', '2022-03-31 18:33:41');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (31, '1Lp5YQzf2hWKxzhNAmTMcpwKUffV2CTJ7y', 'Tequila - Sauza Silver', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', 192.29, 'vulputate luctus cum sociis natoque penatibus', 'proin interdum mauris non ligula pellentesque ultrices', 22, 1, 2.3, '2022-04-09 13:57:25', '2022-08-04 07:28:35');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (32, '1Fi4T7WiiakUVEjk7bPd4whGxLXSEUoaMH', 'Steam Pan Full Lid', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 143.67, 'in blandit ultrices enim lorem ipsum dolor', 'a pede posuere nonummy integer non velit donec', 22, 1, 4.9, '2021-09-21 06:18:21', '2021-11-24 08:59:51');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (33, '12RYrRBitL6UNutHp8ULqVeKNRy7PBWbR8', 'Lamb - Rack', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 136.05, 'porttitor id consequat in consequat', 'dignissim vestibulum vestibulum ante ipsum primis', 45, 1, 3.7, '2021-10-21 21:01:32', '2022-08-16 18:57:01');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (34, '1ERgtJpDcCwqW5Qsn7PcKgMBsKGwSua6y2', 'Wine - Magnotta, White', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 268.34, 'tristique in tempus sit amet', 'odio consequat varius integer ac leo pellentesque ultrices', 100, 0, 3.4, '2022-08-31 13:31:09', '2021-11-09 16:30:30');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (35, '1LUV7TfsHhPppnu7EuCUwRtYRF4ZDicTXt', 'Tobasco Sauce', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 193.46, 'ornare imperdiet sapien urna pretium nisl ut', 'purus aliquet at feugiat non pretium', 23, 0, 3.9, '2021-12-25 13:35:59', '2022-07-27 13:29:16');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (36, '1BKtVuVd1sJwkDANGKwN5ghxrjWxRJbFvj', 'Tray - 12in Rnd Blk', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 335.02, 'duis faucibus accumsan odio curabitur convallis duis consequat', 'proin eu mi nulla ac', 13, 0, 4.2, '2022-03-03 05:35:46', '2021-12-24 14:19:13');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (37, '1Bp9p4uh6JnGar8zWjSdHAbVeMcKTn16P1', 'Steampan Lid', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 173.34, 'commodo vulputate justo in blandit ultrices enim', 'ultrices posuere cubilia curae mauris viverra diam', 19, 0, 4.6, '2022-02-08 21:32:08', '2022-07-12 18:08:41');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (38, '1F4AwwBf7ufNXtNxrtU5cEkk9AdqcdSFZw', 'Glycerine', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 497.47, 'sagittis nam congue risus semper porta volutpat quam', 'suspendisse ornare consequat lectus in est risus', 17, 0, 2.9, '2022-02-24 02:21:19', '2021-09-17 05:30:27');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (39, '1DFMLoPkRJMpFaUAVzsykPiMx44Fp9F17j', 'Cheese - Gorgonzola', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 332.52, 'morbi vel lectus in quam', 'in lectus pellentesque at nulla suspendisse potenti cras', 66, 1, 1.7, '2021-11-04 07:51:14', '2022-06-19 13:17:13');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (40, '1yhCnZr33b13CAPn81xLFGfWnsAa5F7tJ', 'Napkin White - Starched', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 65.1, 'sit amet justo morbi ut odio cras mi pede malesuada', 'erat tortor sollicitudin mi sit amet lobortis sapien', 33, 1, 1.1, '2022-02-10 23:25:04', '2021-10-16 08:05:57');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (41, '1K8jDrf9mwZfZxnkLVUxfk63fge87nukgK', 'Pepperoni Slices', 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', 322.13, 'aliquam quis turpis eget elit', 'sed magna at nunc commodo placerat praesent', 45, 0, 1.7, '2021-10-12 15:29:17', '2021-10-21 00:37:36');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (42, '1Hgy1q81QnRuA8P9SfmAvJw5p6anEUL78g', 'Sugar - Individual Portions', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 78.8, 'eu tincidunt in leo maecenas pulvinar lobortis est', 'tempus vel pede morbi porttitor lorem', 92, 1, 3.1, '2022-06-16 13:31:29', '2022-07-02 03:15:50');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (43, '1JCsniynBCDqkw8wRu48NKHo9oVruWoyLH', 'Muffin Hinge Container 6', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 452.46, 'viverra dapibus nulla suscipit ligula in lacus', 'luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum', 66, 0, 2.9, '2021-09-22 06:05:42', '2021-10-07 17:54:59');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (44, '19nvcqatShJzCmAQKKYAMjaKH8JnFLTTZT', 'Syrup - Golden, Lyles', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 259.51, 'ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean', 'pede ullamcorper augue a suscipit nulla elit ac nulla', 51, 0, 3.2, '2021-10-07 08:34:10', '2022-07-19 10:58:33');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (45, '1AsKGHtrheDZVn2rYybij3Pre8nwe25UFa', 'Cookie Choc', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 222.72, 'sit amet cursus id turpis integer', 'odio odio elementum eu interdum eu tincidunt in leo', 7, 1, 4.8, '2022-08-28 01:30:37', '2022-05-09 19:25:36');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (46, '12JquUv6qFko276J4Numpj4x3aZRaQoiKz', 'Petit Baguette', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 48.15, 'at feugiat non pretium quis lectus', 'dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum', 97, 0, 3.8, '2022-02-08 13:01:00', '2022-03-18 19:18:59');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (47, '1EnV4LyAFVL4V8gKjAYSPFFvYvNCsi1qmW', 'Sambuca - Ramazzotti', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 44.27, 'curabitur at ipsum ac tellus semper interdum mauris', 'penatibus et magnis dis parturient montes nascetur ridiculus', 18, 0, 2.1, '2022-07-17 01:57:20', '2022-07-01 07:52:46');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (48, '1MvzyLPcKkahhx6mRiYtxTSzTcSNs2BS25', 'Wine - Balbach Riverside', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 230.45, 'libero quis orci nullam molestie nibh in lectus pellentesque', 'donec dapibus duis at velit eu est congue elementum in', 36, 1, 4.0, '2022-03-16 19:03:50', '2022-02-10 10:45:21');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (49, '1Bo9qPy151RPhDcYHhcZ5ekzCj1etkhUHn', 'Garlic - Primerba, Paste', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 273.32, 'at turpis a pede posuere nonummy integer', 'fusce lacus purus aliquet at feugiat non pretium', 67, 0, 4.1, '2021-10-06 00:13:48', '2022-08-05 08:45:20');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (50, '15FNuAFdoCW2Ec7tw9Y51CCfoZFPBrps7J', 'Lettuce - Mini Greens, Whole', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 253.72, 'justo pellentesque viverra pede ac diam', 'ante vel ipsum praesent blandit lacinia erat vestibulum sed magna', 22, 1, 2.9, '2021-11-03 14:17:52', '2021-11-20 18:19:06');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (51, '1Chg9WZXf4bGcdD1GxmUL7X1c7qqk7cBYw', 'Eggplant - Asian', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 80.22, 'porttitor id consequat in consequat ut', 'justo sollicitudin ut suscipit a', 80, 1, 1.1, '2021-11-25 23:25:29', '2021-12-04 05:31:26');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (52, '1Vh9dmPVSbu9pDvkQfqjKn1Qigf9P11Za', 'Apron', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 59.85, 'sed nisl nunc rhoncus dui vel sem sed', 'accumsan tortor quis turpis sed', 15, 0, 2.6, '2021-12-28 05:02:25', '2022-08-26 05:35:39');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (53, '15hUcVBGYoKDSQSTQuXsjWLGCnj5wwmMi4', 'Wine - Red, Lurton Merlot De', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 49.84, 'orci eget orci vehicula condimentum curabitur in', 'phasellus in felis donec semper', 65, 1, 3.5, '2022-09-06 19:36:45', '2021-11-29 21:42:29');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (54, '1DMUF8NBTkwxq33BRpDNxG7ghtQEyovmng', 'Soup - Verve - Chipotle Chicken', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 326.64, 'ut suscipit a feugiat et eros vestibulum ac est', 'curae donec pharetra magna vestibulum', 46, 1, 3.8, '2022-02-02 22:54:33', '2021-12-25 15:35:59');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (55, '16Wne94coX9ebQHMPhpUFRGpyajTfxnU5R', 'Compound - Pear', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 207.64, 'felis eu sapien cursus vestibulum proin eu', 'amet eleifend pede libero quis orci nullam', 49, 0, 2.3, '2022-05-23 16:16:53', '2021-11-28 21:11:52');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (56, '17Pr1Rp62NWMjjCGwmpUb5NKWHA7HJjJrY', 'Eggplant - Asian', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 202.77, 'iaculis justo in hac habitasse platea dictumst etiam faucibus cursus', 'mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et', 72, 0, 4.2, '2022-03-03 17:40:03', '2022-09-09 22:33:22');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (57, '1885KnnNQtz18fRftB87ushCQtsusMB2ku', 'Pickle - Dill', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 324.77, 'tellus in sagittis dui vel nisl duis ac nibh fusce', 'curabitur in libero ut massa volutpat convallis morbi', 73, 1, 3.9, '2022-01-02 08:51:56', '2022-05-22 22:49:56');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (58, '18XV4jSzextd4hKcxPJviznmoN1NzxCmEw', 'Coffee - Decaffeinato Coffee', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 431.04, 'quam sapien varius ut blandit non interdum in ante', 'dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis', 61, 0, 3.3, '2022-03-03 01:51:13', '2022-06-17 09:57:01');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (59, '1DD9zk2wmRwVEB3SesVgkV1PAKWYHUE7js', 'Lamb - Loin, Trimmed, Boneless', 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 22.55, 'bibendum felis sed interdum venenatis turpis enim blandit mi', 'pretium quis lectus suspendisse potenti', 31, 0, 2.8, '2021-10-09 04:02:33', '2021-12-12 19:06:10');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (60, '1BNvqf1pk1rKwgXz8KiESt86sagWYedinL', 'Oil - Shortening - All - Purpose', 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 320.87, 'interdum eu tincidunt in leo maecenas pulvinar lobortis', 'placerat ante nulla justo aliquam quis turpis eget', 90, 0, 4.4, '2022-08-07 13:46:44', '2021-09-25 08:16:04');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (61, '15G21etPPjzgnN8jS4GDLsGeTBF8HrhMkd', 'Pepsi - 600ml', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 304.46, 'in hac habitasse platea dictumst etiam', 'consequat ut nulla sed accumsan felis ut at dolor', 59, 0, 3.0, '2022-04-29 17:08:16', '2022-06-13 23:07:36');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (62, '161RWQy8mrZBNhhML9GvF6HatZZRCdSV55', 'Soup - Campbells, Butternut', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 144.8, 'non mi integer ac neque duis bibendum morbi non', 'natoque penatibus et magnis dis parturient', 45, 0, 4.1, '2022-08-25 01:58:10', '2022-03-30 23:16:44');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (63, '1852GmCxB3yVsvjzPGd9vYqATnAPQnqAyk', 'Bread - Raisin Walnut Pull', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 172.85, 'curabitur convallis duis consequat dui nec nisi volutpat eleifend donec', 'in imperdiet et commodo vulputate justo in blandit ultrices enim', 59, 0, 2.9, '2021-10-14 08:05:18', '2022-08-28 22:18:28');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (64, '1D9HhYg3dHYDxSwLmj2bDwzydMnKV5J2e', 'Eggplant - Regular', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 217.93, 'cursus vestibulum proin eu mi', 'in ante vestibulum ante ipsum primis in faucibus orci', 39, 0, 1.1, '2022-06-05 16:58:36', '2021-11-21 18:27:13');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (65, '1NfeHpD5Eo2t4sw2pwXXyCrHpWgPq4qXt9', 'Yogurt - Plain', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 337.65, 'erat quisque erat eros viverra eget congue eget semper rutrum', 'tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum', 25, 1, 3.2, '2022-04-18 07:33:27', '2022-06-12 04:10:17');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (66, '1ELTkzTbfGDfJpH1zCz9MsBW7dZzTvq5TT', 'Cookie Choc', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 416.65, 'dui vel nisl duis ac nibh fusce lacus purus', 'etiam faucibus cursus urna ut tellus nulla', 34, 0, 2.6, '2022-05-14 19:34:06', '2022-03-08 08:36:56');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (67, '1MAZ8yHHSFK5GJwM2mgx8SraJonqD3p7at', 'Shrimp - 31/40', 'In congue. Etiam justo. Etiam pretium iaculis justo.', 320.42, 'duis mattis egestas metus aenean fermentum', 'curabitur at ipsum ac tellus semper', 17, 0, 4.2, '2021-11-19 17:35:08', '2022-04-17 05:47:55');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (68, '1NFrKYGW7F2HwPKjAwpxFz667iYQPDywZX', 'Everfresh Products', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 389.23, 'nullam orci pede venenatis non sodales', 'gravida nisi at nibh in hac habitasse', 34, 1, 1.1, '2022-05-11 04:57:49', '2022-05-10 07:52:31');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (69, '1P3S9gwiK1k1Cm46xLwQvyhtU85mGzUP9Q', 'Steampan - Foil', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 32.03, 'congue vivamus metus arcu adipiscing', 'nonummy integer non velit donec', 57, 0, 3.5, '2022-08-05 09:43:08', '2021-11-30 20:10:40');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (70, '1BWMEwMUfEH4Dpue81gZQi6s19wnMXnfA3', 'Spice - Paprika', 'In congue. Etiam justo. Etiam pretium iaculis justo.', 374.03, 'vulputate elementum nullam varius nulla facilisi cras non', 'diam erat fermentum justo nec condimentum neque sapien placerat', 44, 0, 4.5, '2022-04-26 07:00:45', '2022-09-02 02:53:02');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (71, '1JUk92MwHTWdfRNwKBCh3Cr6WFCevJ4fXn', 'Clams - Littleneck, Whole', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 137.57, 'accumsan tellus nisi eu orci mauris lacinia sapien quis libero', 'blandit mi in porttitor pede justo eu', 7, 0, 4.0, '2022-02-13 23:01:26', '2022-04-12 18:27:19');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (72, '1euem6XAxSrW7nharyWzNaVEJNmYbCPGo', 'Mushroom - Chanterelle Frozen', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 52.99, 'quis odio consequat varius integer ac', 'dui maecenas tristique est et tempus', 31, 0, 1.9, '2022-08-06 04:27:40', '2022-05-04 18:48:34');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (73, '18Mn297j8frred6Q4uHu74PMTMZ8TKvAmT', 'Lettuce Romaine Chopped', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 94.91, 'pede ullamcorper augue a suscipit nulla elit', 'maecenas pulvinar lobortis est phasellus sit amet erat nulla', 85, 1, 4.1, '2021-11-18 19:31:48', '2021-09-28 16:30:47');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (74, '1JQYdY7NrdMxkRGntpQMrmASNJVpTv1ZyM', 'Drambuie', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 405.93, 'curabitur gravida nisi at nibh in hac habitasse platea dictumst', 'eu interdum eu tincidunt in leo maecenas', 19, 0, 1.1, '2021-10-12 12:42:43', '2022-05-03 13:46:07');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (75, '1JdPJYhzKcqYPHrBqyWKJB9CKrgYY9iGD3', 'Wine - Acient Coast Caberne', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', 489.61, 'rutrum nulla nunc purus phasellus in felis', 'non mauris morbi non lectus aliquam sit amet diam', 83, 1, 3.0, '2022-06-27 05:51:56', '2022-07-20 01:19:37');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (76, '1DRxp3e4WPyMJDe1WmJ51Uz7zvnYBqftWo', 'Wine - White, Colubia Cresh', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 469.97, 'justo aliquam quis turpis eget', 'venenatis non sodales sed tincidunt', 8, 1, 4.2, '2021-09-26 17:50:01', '2021-11-14 21:04:00');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (77, '17qT58yzFtBPXH6aMyqVwcytCnGgjoyDmY', 'Milkettes - 2%', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 395.01, 'at nibh in hac habitasse platea dictumst aliquam', 'sit amet cursus id turpis integer aliquet massa', 39, 0, 3.3, '2021-10-16 05:16:42', '2021-10-18 19:46:00');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (78, '1J39AsZjFEbWtof4JQAji3jVunb7uduHER', 'Wine - Maipo Valle Cabernet', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 262.24, 'vel lectus in quam fringilla rhoncus mauris enim leo rhoncus', 'duis bibendum morbi non quam nec dui', 100, 0, 1.9, '2022-06-26 22:03:02', '2022-05-06 22:41:24');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (79, '1E3ZJe1D8k2ANorebRaLbXiqHzm4NpEnLL', 'Mousse - Passion Fruit', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 135.32, 'tempus vivamus in felis eu sapien cursus vestibulum proin eu', 'scelerisque mauris sit amet eros suspendisse accumsan tortor', 72, 0, 4.8, '2022-01-11 03:35:23', '2022-05-17 17:27:15');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (80, '1NBqWSGvUohmVsmQmcr3NuQUYhL3afBBXP', 'Bread - White, Unsliced', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 4.4, 'condimentum neque sapien placerat ante nulla justo aliquam quis', 'id lobortis convallis tortor risus dapibus augue vel accumsan', 14, 0, 4.4, '2022-04-15 14:46:42', '2022-07-13 09:29:30');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (81, '1epKdT5bDwfyugCJvGMauWd1kkRqQTwzi', 'Momiji Oroshi Chili Sauce', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 490.88, 'mattis nibh ligula nec sem duis aliquam convallis', 'nec dui luctus rutrum nulla tellus in', 50, 1, 4.3, '2022-08-28 16:29:47', '2022-09-06 21:40:57');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (82, '1MTxz4wH9SohfTUmMWf5gETospbjXaZ9kF', 'Bread - Pumpernickel', 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 343.87, 'volutpat eleifend donec ut dolor', 'felis donec semper sapien a libero', 39, 1, 4.8, '2022-03-20 20:05:51', '2021-12-18 04:07:11');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (83, '1MBrVuWBu5G3KFujsDMau2RM7cvfAtjBoX', 'Wine - Two Oceans Cabernet', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', 218.56, 'sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl', 'in lectus pellentesque at nulla suspendisse potenti cras in purus', 42, 1, 1.5, '2021-09-18 17:02:04', '2022-08-10 07:07:06');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (84, '16UEKygzw2JKvJBRbyXcchouoLtQon6Bau', 'Tart Shells - Savory, 3', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 194.44, 'dui proin leo odio porttitor id consequat in consequat ut', 'ipsum integer a nibh in quis justo maecenas rhoncus aliquam', 65, 0, 4.1, '2022-05-19 23:45:16', '2021-12-26 22:30:50');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (85, '1K36TWx1AdQf1dEsPpN5yL1b9PccGFBqLX', 'Nantucket - Kiwi Berry Cktl.', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 112.91, 'nunc rhoncus dui vel sem sed sagittis nam congue risus', 'augue luctus tincidunt nulla mollis molestie lorem quisque ut erat', 76, 1, 3.8, '2022-01-13 09:47:18', '2022-06-01 10:09:05');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (86, '15u68WTCfiNxJG1hW8WH5wE1nCHbSYMmCj', 'Cabbage - Green', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 284.34, 'sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis', 'convallis tortor risus dapibus augue vel accumsan tellus nisi', 90, 0, 2.0, '2021-11-11 00:58:22', '2022-05-27 20:30:55');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (87, '1B3MhbmjTHb5oJB7WvmqHcbJinS9atngEB', 'Vinegar - Rice', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 119.41, 'integer aliquet massa id lobortis convallis tortor', 'porttitor lorem id ligula suspendisse ornare consequat', 92, 0, 2.9, '2022-03-30 01:49:00', '2021-09-17 13:34:10');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (88, '1D3htxTUd3Miox83f2kdiD1x4vNSd1muJ3', 'Coffee - Almond Amaretto', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 352.19, 'nulla quisque arcu libero rutrum ac lobortis vel dapibus at', 'turpis a pede posuere nonummy integer non velit donec', 20, 1, 3.3, '2021-12-08 13:14:33', '2022-02-18 14:13:54');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (89, '16gfsjirsK4sUi6qCrfQAnf8Ndr8rz3Dh6', 'Sea Urchin', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 101.05, 'luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum', 'nibh ligula nec sem duis aliquam convallis', 91, 1, 2.7, '2022-04-08 06:56:31', '2022-06-22 05:49:02');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (90, '1MpazQ4dRrutL7XcECHDS5NZxSjcA1NH1D', 'Tart - Pecan Butter Squares', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 286.31, 'venenatis tristique fusce congue diam id ornare imperdiet sapien', 'vestibulum ac est lacinia nisi venenatis tristique fusce congue', 11, 0, 2.1, '2022-04-18 01:59:28', '2022-05-16 21:38:48');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (91, '1KzVqMfLKoT2ogqakkpbNcDddseRaLhppa', 'Wine - Rhine Riesling Wolf Blass', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 239.86, 'porta volutpat erat quisque erat eros viverra', 'sit amet cursus id turpis integer aliquet', 90, 0, 1.0, '2022-05-08 16:16:22', '2022-05-24 15:16:48');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (92, '1AwyCHjConLnj3txsTGZ4JL5gog6wro5KP', 'Cheese - Grana Padano', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 180.81, 'congue vivamus metus arcu adipiscing molestie hendrerit', 'quisque ut erat curabitur gravida nisi at nibh in hac', 42, 1, 2.9, '2022-06-28 01:09:37', '2022-06-24 08:33:08');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (93, '18ZPRWRxUge6aGoPy3L6t4XWqDJc3DVbxF', 'Tart - Pecan Butter Squares', 'Fusce consequat. Nulla nisl. Nunc nisl.', 270.12, 'lacinia aenean sit amet justo morbi ut odio', 'convallis eget eleifend luctus ultricies eu nibh', 31, 0, 1.3, '2022-08-14 01:41:26', '2021-10-21 21:42:52');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (94, '1ArYU96GS9dBWjuX5Aaai4tgZvVgzzRJFY', 'The Pop Shoppe - Lime Rickey', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 405.96, 'quis augue luctus tincidunt nulla mollis', 'felis fusce posuere felis sed lacus morbi sem mauris laoreet', 41, 0, 4.6, '2022-04-20 23:51:43', '2021-11-05 15:12:19');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (95, '17ced88CnqgVXoLuT6tupLx5GqgnDauJVY', 'Yeast - Fresh, Fleischman', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 141.26, 'ante vivamus tortor duis mattis', 'turpis a pede posuere nonummy', 25, 1, 1.4, '2022-03-31 18:06:17', '2022-02-26 04:54:40');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (96, '1GjU1MvzdQkFNJZbPM3LEUoMWoJcyGYXDR', 'Juice - Propel Sport', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 417.16, 'purus sit amet nulla quisque arcu libero rutrum ac', 'eget rutrum at lorem integer tincidunt ante vel ipsum', 61, 1, 2.0, '2021-10-20 11:07:09', '2021-09-19 12:51:40');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (97, '1MqWvdgxKkn94Yviv5AKT28pG3j9y6wngZ', 'Kellogs Special K Cereal', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 487.39, 'a odio in hac habitasse platea dictumst maecenas ut massa', 'elit ac nulla sed vel', 31, 1, 3.8, '2021-10-22 03:55:58', '2022-07-13 14:04:41');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (98, '1KSz94d6xm2TYwUAvhdfpaztR38uvD5X5f', 'Muffin - Mix - Creme Brule 15l', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 159.72, 'erat tortor sollicitudin mi sit amet lobortis sapien', 'scelerisque mauris sit amet eros suspendisse accumsan tortor', 4, 1, 2.2, '2022-02-26 12:38:42', '2022-01-16 04:05:49');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (99, '1C653R4sEZj5L99hrhjm8AQH8pf7dSocbM', 'Honey - Comb', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 455.29, 'eget nunc donec quis orci eget orci vehicula', 'libero ut massa volutpat convallis morbi odio odio elementum eu', 10, 1, 1.2, '2021-11-28 23:31:47', '2022-05-09 17:04:48');
insert into dish (id, _id, Name, Description, Price, Category, Availability, WaitTimeMinutes, SoldOut, Rating, Created, Changed) values (100, '1JFZfVm1r845jP6TWWs1qjGMaQ8Z5gCjY6', 'Wasabi Paste', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 78.75, 'congue elementum in hac habitasse platea', 'luctus et ultrices posuere cubilia curae nulla', 46, 0, 5.0, '2022-08-21 03:36:17', '2022-06-06 01:48:48');
ALTER TABLE dish RENAME COLUMN id TO IDDish;